### ISSUE TITLE
Сделать блог на Jekyll для публикации статей

### ISSUE THREAD

**Issue by A** [A/largescaleJS_ru#1]
- [x] Дизайн [авторского блога](http://addyosmani.com/largescalejavascript/)
- [x] Добавить сноски. мне очень нравятся сноски [как у kizu](http://kizu.ru/blog/ios7/)
- [x] Разместить содержимое файла `00_intro.md` в шапке главной страницы.
- [x] Кнопки «Предыдущая глава»/«Следующая глава» на странице главы 
- [x] Кнопки соц. сетей

**Comment by A** [comment]
Начну, пожалуй, делать блог.

**Comment by A** [comment]
Добавил немного Jekyll. Верстки еще практически нет. Запушил в master, чтобы работать прямо сейчас в той файловой структуре, которая будет после Jekyll. Переводы теперь в `_translations`

**Comment by iamstarkov** [comment]
ок. кстати, как сделаны сноски у кизу?

**Comment by A** [comment]
Основная идея — вот такой селектор: `.sidenote-context:hover + .sidenote`. Вот только я бы позиционировал саму сноску через `pos:a` без указания `top`, вместо `fl:r`.

Вот CSS:
https://github.com/kizu/kizu.github.com/blob/master/s/all.styl#L297

Вот MD:
https://raw.github.com/kizu/kizu.github.com/master/_posts/blog/2013-09-19-ios7.md

Я думаю, можно гораздо скромнее все сделать, но сама идея потрясающая!

**Comment by A** [comment]
В принципе, можно выкатывать на gh-pages, но я еще не работал над дизайном. В этом отношении мне ничего не нравится тут =(

**Comment by A** [comment]
Сделал сноски. В плане кода — стилизовав один класс `.sidenote`.

**Comment by A** [comment]
http://shuvalov-anton.github.io/Patterns-For-Large-Scale-JavaScript-Application-Architecture//
