### ISSUE TITLE
Сделать PDF-версию книги

### ISSUE THREAD

**Issue by A** [A/largescaleJS_ru#104]

**Comment by drugoi** [comment]
Можно еще и версию для печати для олдфагов поправить.

**Comment by A** [comment]
Можно, но я, честно говоря, никогда такого не делал. Если есть желание сделать pull request — пожалуйста)

**Comment by ghost** [comment]
А почему нельзя просто олдфагам распечатать pdf-версию?

**Comment by drugoi** [comment]
@EugeneAbrosimov, действия для скачки pdf-версии (представим, что мне нужна только одна глава): скачать → найти нужную страницу → выставить диапазон страниц для печати → распечатать.
Действия для печатия с сайта: cmd/ctrl+P → печать.
К слову, так можно и сохранить отдельную страницу в PDF.
Совершенно реальный пример взятый из жизни.

**Comment by A** [comment]
Кстати, да. По главе печатать менее удобно, чем печатеть PDF со всей книгой

**Comment by A** [comment]
@drugoi в этом случае, действительно, можно добавить стили для печати. Думаю, хуже от них не будет точно.

**Comment by intech** [comment]
Да, нужно хотя бы в одну страничку собрать все главы, чтобы её можно было и в pdf сохранить, и напечатать.

**Comment by cheshirrrcat** [comment]
Ждем PDF-версию книги :octocat:

**Comment by A** [comment]
Не могу понять, чем сконвертировать md в pdf. Pandoc отказывается, ссылаясь на какие-то странные пакеты. Есть идеи?

**Comment by message** [comment]
@shuvalov-anton https://www.npmjs.org/package/markdown-pdf

**Comment by A** [comment]
@message почему-то он просто вставил скриншоты страниц, ссылки не работают, текст не выделяется.

**Comment by cheshirrrcat** [comment]
Я перевел книгу в PDF. У меня на айпаде все хорошо работает. Всем добра :smiley:
https://www.dropbox.com/s/inw02c71ha7qm8a/largescale-js.pdf

**Comment by A** [comment]
Супер! А как ты это сделал? Все таки нам не один раз придется перевести epub в pdf

**Comment by cheshirrrcat** [comment]
Все просто) Только он не добавляет отступы, чтобы было как сейчас я в Доп.настройках поставил поля 2 см
http://ebook.online-convert.com/ru/convert-to-pdf

**Comment by A** [comment]
Отлично)
