### ISSUE TITLE
Следующая книга

### ISSUE THREAD

**Issue by A** [A/largescaleJS_ru#106]
Если кто-то хочет предложить книгу, можно написать сюда. Самый важный критерий, кроме полезности — это, пожалуй, время. В приоритете книги поменьше)

**Comment by iamstarkov** [comment]
Думаю, что ссылку на этот ишью надо добавить в шаблон страницы, только тогда от него будет польза

**Comment by frenzzy** [comment]
Как на счет еще одной работы Эдди Османи?
**Learning JavaScript Design Patterns / Шаблоны проектирования JavaScript**
http://addyosmani.com/resources/essentialjsdesignpatterns/book/

Начало перевода было положено здесь: http://notabenoid.com/book/42061
Очень хочется видеть его в замечательном удобочитаемом формате как [largescalejs.ru](http://largescalejs.ru/)

**Comment by sadcitizen** [comment]
@Frenzzy Я бы не стал ее переводить. Поясню. На данный момент существует книга Стояна Стефанова "Javascript. Шаблоны.". Они во многом пересекаются. Далее, совсем не давно я в порядке тренировки взялся самостоятельно реализовывать паттерны, опираясь на целый ряд источников (начиная от канонической книжки "банды четырех"). Работой Османи я остался не очень доволен. В некоторых местах он путается, какие то паттерны он и вовсе пробегает поверхностно. В данном случае, я бы предложил силами сообщества написать самостоятельно аналогичный труд, но это уже другая история. Но даже тут будут возникать споры и разногласия, потому что у паттернов весьма широкая трактовка.

**Comment by sadcitizen** [comment]
Можно поискать вот тут: http://jsbooks.revolunet.com/

**Comment by br3t** [comment]
Предлагаю 'Developing Backbone.js Applications' ( https://github.com/addyosmani/backbone-fundamentals )
Даже кто-то начал делать перевод https://github.com/AlexFadeev/backbone-fundamentals

**Comment by sadcitizen** [comment]
@br3t поддерживаю, но вот насколько она актуальна?

**Comment by br3t** [comment]
Если судить по https://github.com/addyosmani/backbone-fundamentals/blob/gh-pages/chapters/00-prelude.md, обновлённому 3 дня назад, то она для версии 1.0.0, а сейчас у backbon'а 1.1.2

**Comment by sadcitizen** [comment]
Отставание на три релиза? Исходя из чейнджлога, я бы не сказал, что они изменили что то фундаментальное.

**Comment by br3t** [comment]
Я как раз склоняюсь к её актуальности

**Comment by RusPosevkin** [comment]
«Developing Backbone.js Applications» на русском языке уже можно почитать, правда за денежку. http://habrahabr.ru/company/piter/blog/212023/

**Comment by gurugray** [comment]
«Functional JavaScript: Introducing Functional Programming with Underscore.js»
http://www.amazon.com/Functional-JavaScript-Introducing-Programming-Underscore-js/dp/1449360726
на первый взгляд кажется полезной :)

**Comment by A** [comment]
@gurugray ее можно перевести? Я имею в виду лицензию

**Comment by gurugray** [comment]
@shuvalov-anton что-то не подумал :( я, к сожалению, не силён в лицензиях :\

**Comment by sadcitizen** [comment]
@gurugray книга стоит денег. К тому же эти книги спустя определенное время появляются в русском переводе. Так что нам никто не даст ее просто так перевести. 

Если и стоит что-то переводить, то оно должно быть открытое для всех.

**Comment by A** [comment]
Обычно это либо Creative Commons лицензия, либо что-то бесплатное (как с этой книгой). В последнем случае, нужно спросить у автора разрешение на перевод.

**Comment by drugoi** [comment]
А как насчет —https://github.com/getify/You-Dont-Know-JS ?
В процессе, но вроде занимательная книга.

**Comment by havenchyk** [comment]
может, статью вроде [этой](http://addyosmani.com/writing-modular-js) ?

**Comment by A** [comment]
@havv мне кажется, AMD уже в прошлом)

**Comment by havenchyk** [comment]
@shuvalov-anton, а вы не могли бы рассказать, почему? толкование для чайников в js :smile:

**Comment by A** [comment]
@havv мне надо проверить свои догадки, так что это пока на уровне имхо. Смысл примерно такой — AMD заставляет программиста писать замыкания и другие подробности самостоятельно. Как мне кажется, это обусловленно тем, что в те времена, когда был популярен AMD системы сборки не были популярны (grunt, gulp, различные CLI), и AMD должен был работать на стороне браузера, чем и объясняются излишние требования. Сейчас же в любом проекте, в котором имеет смысл использовать модульный JS, уже используется сборка Grunt'ом или чем-то подобным: картинки в спрайты, минификация CSS и тд. Так что нет никаких причин выполнять за компьютер его работу и писать замыкания и делать DI модулей самостоятельно, пусть это делает сборщик. Кроме того в CommonJS используется в NodeJS, и большое количество модулей можно установить тривиально, через npm — набрав одну строчку в консоли. Я для компиляции CJS на клиент есть много хороших утилит: [clinch](https://github.com/Meettya/clinch/), [browserify](http://browserify.org/).

Еще раз отмечу — это мое необоснованное личное _мнение_ =)

**Comment by havenchyk** [comment]
@shuvalov-anton, спасибо, популярно и доступно изложили. Правда у меня новые вопросы появились, извините, если это не самое лучшее место для подобного рода вопросов. 
- то есть на текущий момент преимуществом amd (к _requirejs_ тоже относится?) является не представление кода из разных js файлов в виде удобных модулей, а асинхронная загрузка? (что немного спорно для mobile, tablet в условиях плохого покрытия, метро)? Имеет ли вообще смысл использовать amd/requirejs только для асинхронной загрузки (хотя тот же requirejs optimizer склеивает файлы).
- Получается, что _G_(Grunt/Gulp) должен оборачивать код в модули, а не программист руками? Всегда думал, что _G_ больше для минификация, конкатенация и т.п. Или все же надо в стиле CJS писать?

**Comment by A** [comment]
@havv 
- Мне, честно говоря, еще не приходилось использовать асинхронную загрузку (именно загрузку по сети модулей при необходимости), лично мне кажется, что это достаточно редкий кейс (имхо). CJS обеспечивает именно удобную модульность и переиспользование кода.
- Программист пишет CJS модули, но CJS не имеет нативной поддержки в браузере, поэтому обычно при сборке на клиенте такие модули оборачиваеются в замыкания, куда передаются необходимые для работы объекты `require` и `module`, ну и к коду модулей добавляется код, реализующий эти методы. 

Не совсем понял последнее предложение. CommonJS — это node-way код, типа такого: 

```
var m = require('my-module');
m.doSomething('some', 'args');
```

Мы одно и тоже под этим подразумеваем?

**Comment by havenchyk** [comment]
@shuvalov-anton это я неудачно выразился, это и подразумевалось. Спасибо за ответы!

**Comment by A** [comment]
@havv я все-таки рекомендую относиться к тому, что я написал, как к мнению, которое, возможно, в чем-то неправильное) А-то научу еще xDD)

**Comment by A** [comment]
Присматриваюсь к [Single page apps in depth](https://github.com/mixu/singlepageappbook), кажется, хорошая книга. Пока еще не успел прочитать — посмотрел бегло — понравилась. И размером, и содержанием и лицензией. Как вам?

**Comment by br3t** [comment]
Я за :)

**Comment by drugoi** [comment]
@shuvalov-anton я за. По SPA на русском не так много хорошей информации.

**Comment by gurugray** [comment]
тоже за :)

**Comment by havenchyk** [comment]
:+1:

**Comment by sadcitizen** [comment]
@shuvalov-anton я тебе ссылку на нее еще 3 марта твитом скинул, ты только рассмотрел? :)

**Comment by A** [comment]
@instanceofpro Так и есть, плюс только сейчас стало понятно, что есть время на новый перевод :)

**Comment by sadcitizen** [comment]
@shuvalov-anton ну тогда можно начинать.

**Comment by A** [comment]
Пока еще есть несколько сложностей, к примеру, перенос книги Osmani в другой каталог с сохранением ссылок, может быть, где-то через пару недель можно будет начать, если все будет ок со временем

**Comment by sadcitizen** [comment]
Зачем ее куда то переносить? На новую книгу нужно сделать отдельную репу.

**Comment by A** [comment]
Мне кажется логичным все книги собрать на largescalejs.ru

**Comment by sadcitizen** [comment]
Хм, спорный вопрос. Я бы все-таки сделал отдельный репозиторий.

**Comment by br3t** [comment]
Отдельной репой как раз логичней
Просто отвязать largescalejs.ru от репозитария и накидать ссылок на репозитарии с разными книгами

**Comment by A** [comment]
Может быть. В плане разработки, отдельная репа, точно лучше. А вот как-бы  сделать так, чтобы по ссылке `largescalejs.ru/addy-osmany-patterns/` открывалась книга Османи, а не редирект на другие страницы я пока не знаю. Приходит в голову только вариант с подключением отдельных репозиториев через сабмодули git.

**Comment by sadcitizen** [comment]
Ты не хочешь иметь домен еще один?

**Comment by br3t** [comment]
Можно отвязать домен от гитхаба, а потом настроить редиректы какие хочешь

**Comment by sadcitizen** [comment]
@br3t проще поддомены завести и их уже с гитхабу привязать, если это возможно, конечно.

**Comment by A** [comment]
Как вариант. Я хочу, чтобы largescalejs.ru был местом, куда можно было бы придти и почитать хорошие книги по JS на русском, по этому, еще один домен регистрировать не хочется. Ну и пузомерки всякие — тиц, PR, ссылки, все это, думаю, тоже важно для того, чтобы по большему количеству релевантных запросов сайт находили в поиске. Ну и я подумываю о скромной монетизации, как-никак, исключительно на добровольных началах перевести много книг не выйдет :) С этой стороны тоже один домен лучше

**Comment by sadcitizen** [comment]
Тогда надо домен более общий брать, а largescalejs.ru оставить за этой книгой. Кстати, сразу внесу поправку. А почему бы не подключать на страницы с главами комментарии (disqus тот же). Чтобы можно было по месту холиварить.

**Comment by A** [comment]
Пару часов назад как-раз завел таску #127 Действительно надо бы

**Comment by A** [comment]
Прямо сейчас сделаю, пожалуй

**Comment by sadcitizen** [comment]
Ну просто я то как раз собирался так же с делать с документацией по marionette.js

**Comment by A** [comment]
Комментарии к документации? Любопытно)

**Comment by sadcitizen** [comment]
Мне этого всегда не хватало в других местах. Когда есть раздел доков, в комментариях к которому всегда можно задать вопрос и получить ответ.

Нужно создавать условия для общения. Вполне возможно, что у кого то найдутся хорошие дополнения к документации. Кто то просто сможет поделиться опытом. Стоящие комментарии можно будет вообще внести в документацию.

**Comment by A** [comment]
Интересно посмотреть, что из этого выйдет — может очень круто получиться.

**Comment by sadcitizen** [comment]
@shuvalov-anton пойду дальше тогда переводить :) надо еще сайт сделать, а времени мало.

**Comment by A** [comment]
Сделал комменты :)

**Comment by sadcitizen** [comment]
@shuvalov-anton в твиттер напиши об этом
