### ISSUE TITLE
Добавить опенграф-теги

### ISSUE THREAD

**Issue by A** [A/largescaleJS_ru#112]
http://ogp.me/

**Comment by drugoi** [comment]
Чтобы быть точнее:
http://ogp.me/#type_book
http://graph.facebook.com/schema/og/book

**Comment by iamstarkov** [comment]
Ещё можно добавить опенкард теги твиттера и зарегистрировать сайт в
соответствующей тви-программе, и тогда превьюшки в тви будут красивыми
