### ISSUE TITLE
Написать makefile для сборки книг

### ISSUE THREAD

**Issue by A** [A/largescaleJS_ru#113]
Псевдокод:

``` bash
cat translation_ru/*.md --exclude readme.md > epub.md # распечатать все в один файл
epub replace-r  '<!--' '-->' -w '' # Раскомментировать названия глав
makebook ./epub.md # Сборка epub, fb2, pdf, mobi
```

**Comment by gurugray** [comment]
:+1:

**Comment by gurugray** [comment]
Думаю, что и не нужно хранить собраные файлы в репозитории

**Comment by gurugray** [comment]
`epab` и `makebook` что за утилиты?

**Comment by A** [comment]
Это совсем псевдокод, чтобы не забыть. Смысл такой:
1. Склеить все файлы перевода кроме `reamde.md`
2. Раскомментировать заголовки в полученном epub
3. скомпилировать epub, fb2, mobi и pdf из получившегося epub

**Comment by gurugray** [comment]
понятно, пришлю PR

**Comment by A** [comment]
Получилось так:

``` shell
cd ./epub
cat ../_includes/translation/rus/[0-9]*.md | sed 's/<!-- //g' | sed 's/-->//g' > ./_source.md
pandoc epub.md -o largescale-js.epub --toc-depth=2 --epub-cover-image=cover.jpg --epub-chapter-level=2
pandoc epub.md -o largescale-js.fb2 --toc-depth=2 --epub-cover-image=cover.jpg --epub-chapter-level=2
kindleGen -c1 -locale ru  largescale-js.epub -o largescale-js.mobi
```

но `makefile` не сделал.

**Comment by gurugray** [comment]
ну make не страшно, а вот в текущем epab.md другой код это меня смутило, но времени разбиратся небыло, например вот эти
https://github.com/shuvalov-anton/largescaleJS_ru/blame/gh-pages/_includes/translation/rus/04_brainstorming.md#L5

**Comment by A** [comment]
Про код не совсем понял. `{:class="message"}` вроде как использовался изначально.

**Comment by gurugray** [comment]
он был в самих файлах, а в epab его небыло https://github.com/gurugray/largescaleJS_ru/blame/dev/epub/epub.md#L247

**Comment by gurugray** [comment]
там ещё были различия, кажется, но я уже не помню :)

**Comment by A** [comment]
А, я понял. Я `md` сохранял в другой файл, и исключил его из коммита, а `epub.md` я просто забыл удалить. Теперь все ок.

**Comment by gurugray** [comment]
ок, понятно :)
