### ISSUE TITLE
Сделать сниппеты для поисковиков

### ISSUE THREAD

**Issue by A** [A/largescaleJS_ru#116]

**Comment by iamstarkov** [comment]
ты имеешь ввиду микроформаты?

**Comment by A** [comment]
Я знаю, что есть возможность повлиять на поисковый сниппет, и я хочу сделать его более привлекательным. Но я не знаю пока, как это сделать

**Comment by iamstarkov** [comment]
@mistakster писал о своих экспериментах над микроразметкой и сниппетами выдачи в своём блоге, но я не могу найти

**Comment by A** [comment]
https://support.google.com/webmasters/answer/99170?hl=ru
