### ISSUE TITLE
Duplication of paragraphs in part 3

### ISSUE THREAD

**Issue by bruha** [A/largescaleJS_ru#132]
Duplication of paragraphs in part 3, see [screenshot](http://www.clipular.com/c/4609082218512384.png?k=0yrRoAkpAhUbXMO-5aluEe8W7uE)

**Comment by rutsky** [comment]
This issue should be fixed in PR #142

**Comment by rutsky** [comment]
@shuvalov-anton, this issue is fixed in already merged PR #142

**Comment by A** [comment]
fixed in web version. #139 issue is for update ebooks.
