### ISSUE TITLE
Продлить домен largescalejs.ru

### ISSUE THREAD

**Issue by mercuree** [A/largescaleJS_ru#155]
Парни, домен истек, продлите пожалуйста.

**Comment by iamstarkov** [comment]
я работаю над этим

**Comment by A** [comment]
@iamstarkov do you have any updates?

**Comment by A** [comment]
```
created:       2014.01.15
paid-till:     2016.01.15
free-date:     2016.02.15
```

So, we need to wait 2 weeks before I will steal ownership.

**Comment by iamstarkov** [comment]
yep, its true

**Comment by iamstarkov** [comment]
ensure to create ticket on domain buying

**Comment by A** [comment]
Lol) Someone bought the domain :D

**Comment by iamstarkov** [comment]
woot! was thinking its you

**Comment by A** [comment]
Not me. I dunno who has bought it.
