### ISSUE TITLE
Can you summarize this article in 140 characters?

### ISSUE THREAD

**Issue by A** [A/largescaleJS_ru#2]
У меня как-то не получилось объяснить содержимое статьи в твитте. Вот оригинальный текст:

> «Decouple app. architecture w/module,facade & mediator patterns. Mods publish msgs, mediator acts as pub/sub mgr & facade handles security»

**Comment by A** [comment]
> Меньше сязаности. Используйте «модули», «фасад» и «медиатор». «Модули» общаются через «медиатор». «Фасад» обеспечивает безопасность.

**Comment by iamstarkov** [comment]
от меня есть ещё такой вариант

> Меньше связаности: используйте паттерны «модуль», «фасад» и «медиатор». Модули общаются через медиатор. Фасад обеспечит безопасность.

**Comment by A** [comment]
Так немного лучше. Но меня смущает то, что мы ничего не говорим о событиях: 

> ... Mods publish msgs, mediator acts as pub/sub mgr ...

**Comment by A** [comment]
Кстати, я опечатался в слове «сязанности» хД

**Comment by iamstarkov** [comment]
> Так немного лучше. Но меня смущает то, что мы ничего не говорим о событиях:

медиатор по умолчанию работает не через события, верно?

**Comment by A** [comment]
В моей глове перемешались «медиатор», «обсервер», «паблишер/сабскрайбер», «евент-еммиттер», и я потерял нить. Особенно после этого «mediator acts as pub/sub mgr». Может написать как-нибудь так

«... Медиатор обеспечивает взаимодействие между модулями ...»
