### ISSUE TITLE
Добавить favicon

### ISSUE THREAD

**Issue by A** [A/largescaleJS_ru#34]
Ума не приложу, что можно там поместить...

**Comment by iamstarkov** [comment]
Оригинал
[![js](https://f.cloud.github.com/assets/559321/1886722/4916d416-79ed-11e3-8371-512d018a2868.png)](https://f.cloud.github.com/assets/559321/1886722/4916d416-79ed-11e3-8371-512d018a2868.png)

**Comment by iamstarkov** [comment]
Добавил иконку, посмотрите ПР

**Comment by A** [comment]
Нужно добавить в Jekyll [_layouts/page.html](https://github.com/shuvalov-anton/Patterns-For-Large-Scale-JavaScript-Application-Architecture/blob/gh-pages/_layouts/page.html#L3), чтобы закрыть таск.

**Comment by iamstarkov** [comment]
Это необязательно, если иконка лежит в стандартном месте.

**Comment by A** [comment]
Ок, тогда мержу

**Comment by iamstarkov** [comment]
У меня в блоге так и всё работает. в h5bp тоже отказались в какой-то раней версии

**Comment by A** [comment]
Честно говоря, не знал о такой штуке. Теперь буду знать)
