### ISSUE TITLE
Код в тексте выглядит плохо. 

### ISSUE THREAD

**Issue by A** [A/largescaleJS_ru#41]
![screen shot 2014-01-07 at 01 57 35](https://f.cloud.github.com/assets/1410106/1866198/714ac1aa-782a-11e3-952f-e5b9f00e415d.png)

**Comment by iamstarkov** [comment]
картинка побилась

**Comment by A** [comment]
Вроде стало получше
![screen shot 2014-01-08 at 17 57 19](https://f.cloud.github.com/assets/1410106/1867907/0f940d18-785c-11e3-8d20-8da6448b2081.png)

**Comment by iamstarkov** [comment]
хорошо получилось

**Comment by A** [comment]
@matmuchrapna А тут как тебе?
http://largescalejavascript.ru/module-pattern/

**Comment by iamstarkov** [comment]
я бы уменьшил инлайновый код до 15px, чтобы размеры букв совпадали оптически

``` css
    p code {
        font-size: 15px;
    }
```

**Comment by A** [comment]
Да, сделал весь код 15px
