### ISSUE TITLE
Перенос оригинальных акцентов в тексте

### ISSUE THREAD

**Issue by A** [A/largescaleJS_ru#47]
Речь о выделенных цветом блоках.

**Comment by iamstarkov** [comment]
ПОСМОТРЕТ
@
НЕПОНИМАТ
![](http://salesreport.ru/wp-content/uploads/4201.jpg)

**Comment by A** [comment]
Я вот такие штуки пропускал.
![screen shot 2014-01-10 at 23 07 50](https://f.cloud.github.com/assets/1410106/1889333/c9c62f54-7a19-11e3-9686-c78ef81dccc9.png)

**Comment by iamstarkov** [comment]
теперь понимать
