### ISSUE TITLE
Верстка под мобильные

### ISSUE THREAD

**Issue by A** [A/largescaleJS_ru#48]
Думаю, все обойдется добавлением пары `media queries`.

**Comment by A** [comment]
В принципе, на iOS все достаточно сносно, можно не откладывать релиз, а сделать после.

**Comment by iamstarkov** [comment]
если читается и ничего не режет глаз, то конечно

**Comment by iamstarkov** [comment]
можно закрывать? :laughing:

**Comment by A** [comment]
Нужно посмотреть еще. Там с футтером проблема есть.

**Comment by havenchyk** [comment]
Как по мне, большие отступы слева и справа, футер нормально, реклама не очень удобно, случайные клики получаются (или так и задумано :))

**Comment by A** [comment]
Вот это и надо поправить, но я никак не могу найти время =(

**Comment by A** [comment]
Кликов, там, к сожалению, от силы штуки 2-3 в неделю, и то не мобильные, так что умысла никакого там нет.

**Comment by A** [comment]
Пока, я думаю, можно закрыть, тк основную багу с налезающим на контент футтером я исправил
