### ISSUE TITLE
/dev.html

### ISSUE THREAD

**Issue by A** [A/largescaleJS_ru#49]
На странице `index.html` будут только вычитанные и опубликованные главы. На странице `dev.html` будут все переведенные главы, включая опубликованные и не опубликованные.

**Comment by A** [comment]
Наверное, все таки лучше использовать `--drafts`. Изначально думал предложить краудсорсинг, типа «если вам интересно, что дальше — помогите вычитать вот тут все», а сейчас подумал, что вряд ли я хочу чтобы у пользователей была такая возможность в обход гитхаба. Они же просто прочитают невычитанный перевод и забьют, а на нормальный уже не будут возвращаться.

**Comment by iamstarkov** [comment]
> Они же просто прочитают невычитанный перевод и забьют, а на нормальный уже не будут возвращаться.

верно
