### ISSUE TITLE
Ссылка «Следите за публикациями в Twitter»

### ISSUE THREAD

**Issue by A** [A/largescaleJS_ru#50]
Не все пользуются RSS, по этому я завел аккаунт в Twitter — [@LargeJS](https://twitter.com/LargeJS), в котором я планирую публиковать ссылки на новые переводы два раза в неделю.

**Comment by iamstarkov** [comment]
хорошая идея

**Comment by A** [comment]
[Добавил иконку твиттера](https://github.com/shuvalov-anton/Patterns-For-Large-Scale-JavaScript-Application-Architecture/commit/44d0a122caf3f63b683018592758e2d8006f08b8) рядом с иконкой RSS. И в лиде написал «Следите за публикациями в твиттере или рсс». Надеюсь этого хватит)

**Comment by A** [comment]
Вообще, у я думаю, что можно будет позднее взять еще одну книгу, тогда фолловеры в твиттере будут весьма полезны. Но это пока очень смутно, конечно.

**Comment by iamstarkov** [comment]
В лиде ошибки:
- RSS ссылается на твиттер
- в последних двух строчках «публикация» встречается три раза

**Comment by iamstarkov** [comment]
для RSS лучше использовать feedburner

**Comment by iamstarkov** [comment]
> Вообще, у я думаю, что можно будет позднее взять еще одну книгу, тогда фолловеры в твиттере будут весьма полезны. Но это пока очень смутно, конечно.

нужно будет делать отдельным проектом, да. но это если здесь взлетит

**Comment by A** [comment]
> для RSS лучше использовать feedburner

Какие плюсы это дает?

**Comment by A** [comment]
Лид поправил в #51, посмотри, так лучше?

**Comment by iamstarkov** [comment]
да
