### ISSUE TITLE
Добавить свой лид о книге + информацию о формате публикаций 

### ISSUE THREAD

**Issue by A** [A/largescaleJS_ru#51]
Думаю, что сейчас можно заменить лид из книги, на свой лид, и написать о том, что книга находится в процессе перевода, и регулярно, 2 раза в неделю будет публиковаться новая глава.

**Comment by A** [comment]
@matmuchrapna @freetonik думаете так будет ок?

**Comment by iamstarkov** [comment]
думаю, что не совсем. Надо оставить оригинальный лид из книги, а перед ним опубликовать вступление «от переводчика»

**Comment by A** [comment]
Понял. А то, что я написал, по твоему, сгодится как вступление от переводчика?

**Comment by iamstarkov** [comment]
конечно

**Comment by A** [comment]
Закрываю таск
