### ISSUE TITLE
Информация о переводе

### ISSUE THREAD

**Issue by A** [A/largescaleJS_ru#53]
Список участников и контакты (twitter/web-site)...

Возможно, стоит заменить эту строку:

> «Автор: Addy Osmani. Технический обзор: Andrée Hansson»

**Comment by iamstarkov** [comment]
Можно сделать так:

> Оригинал: «Автор: Addy Osmani. Технический обзор: Andrée Hansson»
> Перевод:  {…}

**Comment by A** [comment]
@matmuchrapna @freetonik Посмотрите футтер

**Comment by freetonik** [comment]
Все ок.

**Comment by iamstarkov** [comment]
мне неудобно, что я попал после слова «перевод». моя роль меньше или другая =(

**Comment by A** [comment]
> мне неудобно, что я попал после слова «перевод». моя роль меньше или другая =(

Как лучше написать? Я, если честно, просто не знаю как называется ваша с Рахимом роль.

**Comment by freetonik** [comment]
Аналогично, но я себя успокоил тем, что перевод это продукт, и мы работаем над ним.
Или я могу перевести пару глав :)

**Comment by A** [comment]
Так я уже все перевел — ничего не осталось хД) Могу написать «коррекция перевода», или «редакторы», не знаю как правильно.

**Comment by iamstarkov** [comment]
давайте поменяем на «Перевод» на «(Авторы | Авторы перевода)» или «Организаторы» и тогда уже можно будет говорить о продукте
вы как думаете?

**Comment by A** [comment]
=(
![560824](https://f.cloud.github.com/assets/1410106/1923290/78f5eeaa-7e12-11e3-8548-0864b9d09cb2.gif)

**Comment by iamstarkov** [comment]
«Участники перевода» вот!

**Comment by iamstarkov** [comment]
если воспринимать не как продукт, а как процесс, то подходит абсолютно

**Comment by A** [comment]
А в целом как будет? Может быть:

> Перевод: Антон Шувалов. Помощь в переводе: Владимир Старков, Рахим Давлеткалиев

**Comment by iamstarkov** [comment]
такой вариант мне кажется более честным и больше нравится

**Comment by freetonik** [comment]
Ñîãëàñåí.

**Comment by iamstarkov** [comment]
кодировка в гитхаб-имейл реплаях побилась

**Comment by freetonik** [comment]
Я же говорю – Ñîãëàñåí!

**Comment by freetonik** [comment]
:) извините, на шутки потянуло
я сказал "согласен".
