### ISSUE TITLE
привести адрес репозитория и адрес в твиттере к адресу сайта (имею ввиду largescalejavascript)

### ISSUE THREAD

**Issue by iamstarkov** [A/largescaleJS_ru#54]
сабж

профиты:
- единобразие
- понятнее

**Comment by A** [comment]
Я за. Для этого нужно перерегистрировать аккаунт в тви? На гитхабе можно просто перименовать репо — ссылки не должны побиться.

**Comment by A** [comment]
Увы, «largescalejavas» — это максимум того, на что способен твиттер.

**Comment by A** [comment]
Изначально я хотел назвать тви так — https://twitter.com/largescalejs . Но он занят.

**Comment by iamstarkov** [comment]
может так? 

twitter/largescaleJS_ru
github/largescaleJS_ru
largescaleJS.ru (домен могу купить)

**Comment by A** [comment]
Давай. Я, на самом деле, думал, что я немного поторопился с доменом — длинный получился.

**Comment by iamstarkov** [comment]
зато прикольный

**Comment by A** [comment]
А где ты будешь домен покупать? Я, по-моему, за 100 рублей купил. Могу еще раз, если ты на мастер-хосте за 500 покупать решил хД)

**Comment by iamstarkov** [comment]
не продлевай его потом =)

**Comment by iamstarkov** [comment]
я за 99 рублей на regod.ru могу купить

**Comment by A** [comment]
Бери тогда) Я вот не могу вспомнить где брал

**Comment by A** [comment]
Добавь в `CNAME` как DNS настроишь тогда, а старый, наверное, лучше удалить, чтобы путанницы не было. Сейчас тви переименую.

**Comment by A** [comment]
> github/largescaleJS_ru

Это ты об организации что-ли?

**Comment by iamstarkov** [comment]
нет. это оформительское

**Comment by A** [comment]
Переименовал репо, и тви. По домену создал таск. #56

**Comment by iamstarkov** [comment]
урл репо не совпадает с урлом тви

**Comment by A** [comment]
Спасибо! Просмотрел!
