### ISSUE TITLE
провязка с prose.io

### ISSUE THREAD

**Issue by iamstarkov** [A/largescaleJS_ru#55]
что думаете?

мне кажется, это самый удобный вариант получения правок для всех

**Comment by A** [comment]
Ну, я на самом деле не понял, чем prose.io удобен для работы, но вот для правок от пользователей он, стопудов удобен. Ты об этом?

**Comment by iamstarkov** [comment]
да.

нам он удобен, что пользователям не надо объяснять как прислать правки

**Comment by A** [comment]
Давай, сделаешь? Это до релиза лучше сделать?

**Comment by iamstarkov** [comment]
это некритично, но тем не менее жутко полезно, особенно если набегут гики с хабра

**Comment by iamstarkov** [comment]
попробую, но не могу обещать
