### ISSUE TITLE
Купить и привязать домен largescalejs.ru

### ISSUE THREAD

**Issue by A** [A/largescaleJS_ru#56]

**Comment by iamstarkov** [comment]
домен купил. он пока в очереди на оформление, как станет доступным, так поменяю dns

**Comment by A** [comment]
Тут все правильно, но я почему-то подумал, что закрыл эту ишью.

**Comment by iamstarkov** [comment]
пройди по ссылкам(#19 #10) и ты всё поймёшь

**Comment by iamstarkov** [comment]
@shuvalov-anton не забудь обновить урл сайта в описании репозитория

**Comment by iamstarkov** [comment]
готово http://largescalejs.ru/

**Comment by A** [comment]
Ага! Я уже как час пользуюсь
