### ISSUE TITLE
несчитываемая фавиконка в браузере

### ISSUE THREAD

**Issue by iamstarkov** [A/largescaleJS_ru#57]
у меня полосочки сливаются в кирпич, а у вас?

**Comment by A** [comment]
Да, то же самое . Можно две полоски сделать, где одна чуть больше другой, чтобы читалось лучше, что это книги.

**Comment by iamstarkov** [comment]
я думаю можно и три оставить только уменьшить их

**Comment by iamstarkov** [comment]
я поэкспериментирую сегодня

**Comment by A** [comment]
Как-то так имел в виду
![fav 1-128](https://f.cloud.github.com/assets/1410106/1923778/c6b107fe-7e19-11e3-9860-da496caeb7a5.gif)
![fav 1](https://f.cloud.github.com/assets/1410106/1923779/c6b25e38-7e19-11e3-8540-4f7c7b802fc6.gif)

**Comment by iamstarkov** [comment]
тогда их лучше повернуть на бок и пусть две стоят ровно, а одна прислонённая (под наклоном)

**Comment by A** [comment]
Интересная идея, попробуй!

**Comment by A** [comment]
Может быть все в порядке?
![uzbagoysya_29146988_orig_](https://f.cloud.github.com/assets/1410106/2196654/6d37bf52-98b2-11e3-932c-1e7113f2d9c9.jpeg)

**Comment by iamstarkov** [comment]
раз опубликовались и всё ок, значит точно всё хорошо
