### ISSUE TITLE
Версия для электронных книг

### ISSUE THREAD

**Issue by A** [A/largescaleJS_ru#66]
Возможно есть смысл сделать версию для читалок (epub, mobi, ...). Нужно посмотреть лицензию, дает ли она на это права.

**Comment by defshift** [comment]
+1

**Comment by havenchyk** [comment]
+1

**Comment by Nea88** [comment]
+1

**Comment by ghost** [comment]
Лицензия это позволяет сделать, но при условии, что книга будет выложена в сеть бесплатно. То есть продавать ее нельзя будет.

**Comment by A** [comment]
@EugeneAbrosimov Отлично! А можно пруф-линк? Где смотреть лицензию?

**Comment by A** [comment]
https://twitter.com/shuvalov_anton/status/438591463086387200

**Comment by ghost** [comment]
@shuvalov-anton я видимо перепутал с другой его книгой. Книгу про паттерны можно выложить в сеть.

**Comment by ghost** [comment]
А вот и ответ https://twitter.com/addyosmani/status/438684364860571648

**Comment by havenchyk** [comment]
круто, а можно из md в epub без проблем перегнать?

**Comment by iamstarkov** [comment]
@VladimirHavenchyk  мы думаем попробовать pandoc и https://leanpub.com/

**Comment by A** [comment]
Сделал. Посмотрите, пожалуйста, нет ли багов в тексте. [Ссылка на epub](http://largescalejs.ru/epub/largescale-js.epub)

**Comment by A** [comment]
[mobi](http://largescalejs.ru/epub/largescale-js.mobi), [epub](http://largescalejs.ru/epub/largescale-js.epub), [fb2](http://largescalejs.ru/epub/largescale-js.fb2)

**Comment by ghost** [comment]
Обложку надо бы.

**Comment by havenchyk** [comment]
Можно попробовать заголовки глав выделить, например, с новой страницы начинать (перед заголовком оставлять пустое место). Можно посмотреть, как сделано в книжке по python http://swaroopch.com/notes/python/#download . Это я про epub

**Comment by A** [comment]
@VladimirHavenchyk да, там что-то с форматом текста не ок — выключка по ширине, заголовки не разбиты. Попробую разобраться с опциями pandoc.
@EugeneAbrosimov Да. Пожалуй, нарисую =)

**Comment by A** [comment]
- [x] Выяснить размеры обложки
- [x] Нарисовать
- [x] Выяснить, как можно начинать каждую главу с новой страницы (Либо через опции pandoc, либо через форматирование md)

**Comment by A** [comment]
Обновил: [mobi](http://largescalejs.ru/epub/largescale-js.mobi), [epub](http://largescalejs.ru/epub/largescale-js.epub), [fb2](http://largescalejs.ru/epub/largescale-js.fb2)

**Comment by A** [comment]
Посмотрите еще раз, нет ли проблем

**Comment by havenchyk** [comment]
epub посмотрел. все равно заголовки новых глав сразу за текстом идут, не с новой страницы.

**Comment by A** [comment]
@VladimirHavenchyk у меня идут с новой страницы. Я тольк `H2` с новой страницы сделал, как на сайте. Может быть в этом дело? https://www.dropbox.com/s/nxlejt87713z92a/Screenshot%202014-03-02%2012.07.42.png

**Comment by A** [comment]
Все ок? Закрываю ишью?

**Comment by havenchyk** [comment]
Mobi не проверил, epub пойдет, в fbreader для андроида главы не с новой страницы, но пойдет. В случае чего еще issues создать можно

**Comment by A** [comment]
Отлично! Разместил ссылки на главной! Всем спасибо за участие)
