### ISSUE TITLE
typo.js ломает примеры кода

### ISSUE THREAD

**Issue by A** [A/largescaleJS_ru#73]
@matmuchrapna код зачем-то тоже типографируется.
![screenshot 2014-01-21 21 44 46](https://f.cloud.github.com/assets/1410106/1964857/04833712-82b3-11e3-9c3b-c50fd2872e62.png)

**Comment by A** [comment]
![screenshot 2014-01-21 21 46 23](https://f.cloud.github.com/assets/1410106/1964866/36849ad0-82b3-11e3-8bcc-95a5fa57d710.png)

**Comment by iamstarkov** [comment]
А без него лучше?

**Comment by A** [comment]
Да, я пока выключил.

**Comment by iamstarkov** [comment]
уже на сайте можно посмотреть?

**Comment by iamstarkov** [comment]
надо его выпилить

**Comment by iamstarkov** [comment]
Спасибо
