### ISSUE TITLE
Побилась базовая линия в тексте про лицензию

### ISSUE THREAD

**Issue by iamstarkov** [A/largescaleJS_ru#92]
сабж

**Comment by A** [comment]
Браузер? Скриншот?

**Comment by A** [comment]
Это, типа, ок:
![screenshot 2014-02-11 10 23 03](https://f.cloud.github.com/assets/1410106/2134025/3bf49f5c-92d4-11e3-88ad-07e613a8bd50.png)

**Comment by A** [comment]
Хотя. Думаю, можно убрать текст.

**Comment by iamstarkov** [comment]
Не ок, базовая линия уходит вниз у ссылки

**Comment by A** [comment]
Увидел и понял почему. Поправлю
